# Generated by Django 2.0.2 on 2018-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('lore', models.TextField()),
                ('pantheon', models.TextField()),
                ('role', models.TextField()),
                ('title', models.TextField()),
                ('type', models.TextField()),
                ('card_url', models.URLField()),
                ('icon_url', models.URLField()),
                ('latest_god', models.BooleanField()),
                ('hp', models.FloatField()),
                ('mp', models.FloatField()),
                ('hp5', models.FloatField()),
                ('mp5', models.FloatField()),
                ('hp_pl', models.FloatField()),
                ('mp_pl', models.FloatField()),
                ('hp5_pl', models.FloatField()),
                ('mp5_pl', models.FloatField()),
                ('speed', models.PositiveIntegerField()),
                ('mag_protection', models.FloatField()),
                ('mag_protection_pl', models.FloatField()),
                ('phy_protection', models.FloatField()),
                ('phy_protection_pl', models.FloatField()),
                ('mag_power', models.FloatField()),
                ('mag_power_pl', models.FloatField()),
                ('phy_power', models.FloatField()),
                ('phy_power_pl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('tier', models.IntegerField()),
                ('price', models.IntegerField()),
                ('root_item_id', models.PositiveIntegerField()),
                ('short_description', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('starting_item', models.BooleanField()),
                ('type', models.TextField()),
                ('icon_id', models.PositiveIntegerField()),
                ('icon_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('avatar_url', models.URLField()),
                ('name', models.TextField()),
                ('level', models.PositiveIntegerField()),
                ('mastery_level', models.IntegerField()),
                ('clan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('clan_name', models.TextField(blank=True, null=True)),
                ('total_worshippers', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('leaves', models.IntegerField()),
                ('created', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
