# Generated by Django 2.0.2 on 2018-05-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('icon_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='god',
            name='atk_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='god',
            name='atk_speed_pl',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='god',
            name='ability_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ability_1', to='smite.Ability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='god',
            name='ability_2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ability_2', to='smite.Ability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='god',
            name='ability_3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ability_3', to='smite.Ability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='god',
            name='ability_4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ability_4', to='smite.Ability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='god',
            name='ability_passive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ability_passive', to='smite.Ability'),
            preserve_default=False,
        ),
    ]
