# Generated by Django 2.0.2 on 2018-05-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smite', '0002_auto_20180514_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.TextField()),
                ('value', models.TextField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smite.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemdescription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemdescription',
            name='value',
        ),
        migrations.AddField(
            model_name='itemdescription',
            name='aura',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdescription',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smite.Item'),
            preserve_default=False,
        ),
    ]
