# Generated by Django 2.0.2 on 2018-05-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smite', '0004_auto_20180514_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='description',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
