# Generated by Django 2.0.2 on 2018-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smite', '0005_ability_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='god',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
